### ISSUE TITLE
Problem with L-BFGS training

### ISSUE THREAD

**Issue by tbluche** [clementfarabet/ipam-tutorials#13]
Hi,

I've installed everything on my computer and tried to run the scripts of today's session, and that works fine until L-BFGS. I have the error below. This actually happens in autodiff code, maybe I don't have the right version (?)

```
Starting L-BFGS
Traceback (most recent call last):
  File "train_svm.py", line 72, in <module>
    sys.exit(main())
  File "train_svm.py", line 64, in main
    m=lbfgs_m)
  File "/usr/local/lib/python2.7/dist-packages/pyautodiff-0.0.1-py2.7.egg/autodiff/fmin_scipy.py", line 119, in fmin_l_bfgs_b
    f_df, lvars  = theano_f_df(fn, args, mode=theano_mode)
  File "/usr/local/lib/python2.7/dist-packages/pyautodiff-0.0.1-py2.7.egg/autodiff/fmin_scipy.py", line 72, in theano_f_df
    memo=dict(zip(orig_s_args, s_args)))
TypeError: clone_get_equiv() got an unexpected keyword argument 'memo'
```

**Comment by jaberg** [comment]
Thanks for reporting. This is a known issue that would be solved by updating Theano to use the development head.

The server running the IPAM tutorials is actually running this branch:
https://github.com/jaberg/Theano/tree/ipam2012

There are a few tweaks there wrt the development head that make PyAutoDiff work better, I'm hoping that those changes will be merged to Theano master soon, and then I'll update the ipam-tutorial README.md with installation instructions.

**Comment by tbluche** [comment]
Oh good that works great, cheers!
